import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { MainLayoutContainer, Navbar, Sidebar } from "@/components";
import { SidebarProvider } from "@/context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <div className="min-h-screen flex flex-grow flex-col bg-black/[.925] ">
            <Navbar />

            <div className="flex-1 flex flex-col sm:flex-row m-4 gap-4">
              <Sidebar />
              <MainLayoutContainer>
                <div className="absolute inset-0 overflow-auto">
                  {/* This is where main content goes */}
                  {children}
                  {/* Main Content End */}
                </div>
              </MainLayoutContainer>
            </div>

            {/* <MediaPlayer /> */}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
